package com.irving.cursoKubernetes.infraestructure.helper;


import com.irving.cursoKubernetes.api.models.responses.ApiResponseDto;
import com.irving.cursoKubernetes.api.models.responses.TourResponseDto;
import com.irving.cursoKubernetes.domain.entities.ReservationEntity;
import com.irving.cursoKubernetes.domain.entities.TourEntity;
import com.irving.cursoKubernetes.domain.mappers.TourMapper;
import com.irving.cursoKubernetes.domain.repositories.TourRepository;
import jakarta.transaction.Transactional;
import lombok.AllArgsConstructor;
import org.springframework.stereotype.Component;

import java.util.Set;

@Transactional
@Component
@AllArgsConstructor
public class TourEntityBuilder {

private final TourRepository tourRepository;
private final TourMapper tourMapper;



    public TourEntity tourEntityBuilderAndSave(Long id, Set<TicketEntity> tickets, Set<ReservationEntity> reservations, CustomerEntity customer) {

        return this.tourRepository.save(
                TourEntity.builder()
                        .id(id) // ID will be generated by the database if null
                        .tickets(tickets)
                        .reservations(reservations)
                        .customer(customer)
                        .build()
        );

    }


    public ApiResponseDto<TourResponseDto> toTourResponseDto(TourEntity tourEntity) {
        var tourEntityToDto= this.tourMapper.toTourResponseDto(tourEntity);
        return ApiResponseDto.<TourResponseDto>builder()
                .status("success")
                .statusCode(200)
                .message("Tour created successfully")
                .data(tourEntityToDto).build();
    }


}
