package com.irving.cursoKubernetes.infraestructure.services;

import com.irving.cursoKubernetes.api.models.request.TourRequestDto;
import com.irving.cursoKubernetes.api.models.responses.ApiResponseDto;
import com.irving.cursoKubernetes.api.models.responses.CustomerResponseDto;
import com.irving.cursoKubernetes.api.models.responses.TourResponseDto;
import com.irving.cursoKubernetes.domain.entities.HotelEntity;
import com.irving.cursoKubernetes.domain.entities.ReservationEntity;
import com.irving.cursoKubernetes.domain.mappers.TourMapper;
import com.irving.cursoKubernetes.domain.repositories.TourRepository;
import com.irving.cursoKubernetes.infraestructure.abstract_services.ITourService;
import com.irving.cursoKubernetes.infraestructure.client.CustomerClient;
import com.irving.cursoKubernetes.infraestructure.helper.EntityLoader;
import com.irving.cursoKubernetes.infraestructure.helper.TourEntityBuilder;
import com.irving.cursoKubernetes.infraestructure.helper.TourHelper;
import jakarta.persistence.EntityNotFoundException;
import jakarta.transaction.Transactional;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

@Transactional
@Service
@RequiredArgsConstructor
public class TourService implements ITourService {

    private final TourRepository tourRepository;
    private final CustomerClient customerClient;
    private final TourHelper tourHelper;
    private final TourMapper tourMapper;
    private final TourEntityBuilder tourEntityBuilder;
    private final EntityLoader entityLoader;
    private final CustumerIncreasTicketsAndReservations custumerIncreasTicketsAndReservations;

    @Override
    public ApiResponseDto<TourResponseDto> create(TourRequestDto request) {
       // 1. Get the Customer from Microservices msvc-users
        var customerResponse = this.customerClient.getCustomerById(request.getIdClient());
        if (customerResponse == null || customerResponse.getData() == null) {
            throw new EntityNotFoundException("Customer not found with ID: " + request.getIdClient());
        }
        var customerFindByIdDto = customerResponse.getData();

//        var customerFindById = entityLoader.findCustumerEntityById(request.getIdClient());

        var flightsFIndById = new HashSet<FlyEntity>();
        request.getIdFlys().forEach(flyRequest -> flightsFIndById.add(this.entityLoader.findFlyEntityById(flyRequest.getIdFly())));

        var hotels = new HashMap<HotelEntity, Integer>();
        request.getIdHotels().forEach(hotelRequest -> hotels.put(this.entityLoader.findHotelEntityById(hotelRequest.getIdHotel()), hotelRequest.getTotalDays()));

        Set<TicketEntity> ticketsCreatedToSave = this.tourHelper.createTickets(flightsFIndById, customerFindById);
        Set<ReservationEntity> reservationsCreatedToSave = this.tourHelper.createReservations(hotels, customerFindByIdDto);

        var tourToSave = tourEntityBuilder.tourEntityBuilderAndSave(
                null, // ID will be generated by the database
                ticketsCreatedToSave,
                reservationsCreatedToSave,
                customerFindById
        );
        this.custumerIncreasTicketsAndReservations.increaseTicketsAndReservations(customerFindById.getDni(), TourService.class);
        return this.tourEntityBuilder.toTourResponseDto(tourToSave);
    }




    @Override
    public ApiResponseDto<TourResponseDto> read(Long id) {
        TourResponseDto tourEntityToDto = tourMapper.toTourResponseDto(
                this.entityLoader.findTourEntityById(id));
        return ApiResponseDto.<TourResponseDto>builder()
                .status("success")
                .statusCode(200)
                .message("Tour retrieved successfully")
                .data(tourEntityToDto)
                .meta(null)
                .build();
    }

    @Override
    public ApiResponseDto<TourResponseDto> update(Long id, TourRequestDto request) {
        var tourEntity = entityLoader.findTourEntityById(id);
        var customer = entityLoader.findCustumerEntityById(request.getIdClient());

        var flights = new HashSet<FlyEntity>();
        request.getIdFlys().forEach(flyRequest ->
                flights.add(entityLoader.findFlyEntityById(flyRequest.getIdFly())));

        var hotels = new HashMap<HotelEntity, Integer>();
        request.getIdHotels().forEach(hotelRequest ->
                hotels.put(this.entityLoader.findHotelEntityById(hotelRequest.getIdHotel()), hotelRequest.getTotalDays()));

        var tourToSave = tourEntityBuilder.tourEntityBuilderAndSave(
                tourEntity.getId(), // ID will be used to update the existing tour
                this.tourHelper.createTickets(flights, customer),
                this.tourHelper.createReservations(hotels, customer),
                customer
        );

        TourResponseDto tourEntityToDto = tourMapper.toTourResponseDto(tourToSave);
        return ApiResponseDto.<TourResponseDto>builder()
                .status("success")
                .statusCode(200)
                .message("Tour update successfully")
                .data(tourEntityToDto)
                .build();
    }

    @Override
    public ApiResponseDto<Void> delete(Long id) {
        tourRepository.delete(this.entityLoader.findTourEntityById(id));
        return ApiResponseDto.<Void>builder()
                .status("success")
                .statusCode(200)
                .message("Tour deleted successfully")
                .build();
    }

    @Override
    public ApiResponseDto<TourResponseDto> addTicket(Long flyId, Long tourId) {
        var tourEntity = this.entityLoader.findTourEntityById(tourId);
        var flyEntity = this.entityLoader.findFlyEntityById(flyId);
        Set<FlyEntity> flyEntities = Set.of(flyEntity);
        var customer = tourEntity.getCustomer();
        var newTickets = tourHelper.createTickets(flyEntities, customer);
       newTickets.forEach(tourEntity::addTicket);
        var updatedTour = tourRepository.save(tourEntity);
        this.custumerIncreasTicketsAndReservations.increaseTicketsAndReservations(
                tourEntity.getCustomer().getDni(), TourService.class);
        TourResponseDto tourResponseDto = tourMapper.toTourResponseDto(updatedTour);
        return ApiResponseDto.<TourResponseDto>builder()
                .status("success")
                .message("Ticket added successfully")
                .data(tourResponseDto)
                .build();
    }

    @Override
    public ApiResponseDto<TourResponseDto> removeTicket(UUID ticketId, Long tourId) {
        var tourEntity = this.entityLoader.findTourEntityById(tourId);
        tourEntity.removeTicket(ticketId);
        var updatedTour = tourRepository.save(tourEntity);
        // Save the updated tour
        var tourDto = tourMapper.toTourResponseDto(updatedTour);
        return ApiResponseDto.<TourResponseDto>builder()
                .status("success")
                .statusCode(200)
                .message("Ticket removed successfully")
                .data(tourDto)
                .build();
    }


    @Override
    public ApiResponseDto<TourResponseDto> addReservation(UUID reservationId, Long tourId) {
        var tourEntity =this.entityLoader.findTourEntityById(tourId);
        var reservationEntity = this.entityLoader.findReservationEntityById(reservationId);
        tourEntity.addReservation(reservationEntity);
        var updatedTour = tourRepository.save(tourEntity);
        this.custumerIncreasTicketsAndReservations.increaseTicketsAndReservations(
                tourEntity.getCustomer().getDni(), TourService.class);
        var tourDto = tourMapper.toTourResponseDto(updatedTour);
        return ApiResponseDto.<TourResponseDto>builder()
                .status("success")
                .statusCode(200)
                .message("Reservation added successfully")
                .data(tourDto)
                .build();
    }



    @Override
    public ApiResponseDto<TourResponseDto> removeReservation(UUID reservationId, Long tourId) {
        var tourEntity = tourRepository.findById(tourId)
                .orElseThrow(() -> new EntityNotFoundException("Tour not found"));
        tourEntity.removeReservation(reservationId);
        var updatedTour = tourRepository.save(tourEntity);
        var tourDto = tourMapper.toTourResponseDto(updatedTour);
        return ApiResponseDto.<TourResponseDto>builder()
                .status("success")
                .statusCode(200)
                .message("Reservation removed successfully")
                .data(tourDto)
                .build();

    }



}
