# ==========================================
# 1. DEFINICIÓN DE VARIABLES GLOBALES
# ==========================================
@hostname = localhost
@port = 8081
@host = http://{{hostname}}:{{port}}
@page = 1
@size = 100



### Petición GET Protegida ###
GET {{host}}/api/v1/fly/findAll?page={{page}}&size={{size}}
