spring.application.name=mvc-users

spring.profiles.active=dev

logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n
# se usa para configurar el servidor embebido en Spring Boot en lugar de ponerlo en el controlador url /api/v1/nameControlador
server.servlet.context-path=/api/v1

### Config Flyway ###
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration
spring.flyway.out-of-order=true
spring.flyway.clean-disabled=true
spring.flyway.validate-on-migrate=true


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 2. Habilita el log de las consultas SQL
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.hibernate.SQL=DEBUG
spring.jpa.properties.hibernate.use_sql_comments=true
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.docker.compose.enabled=false