### Configuration DB ###
spring.datasource.url=jdbc:postgresql://localhost:5431/db_users
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD_USER}

### Configuration HikariCP Pool of connections###
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=10

# Eureka Local
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

### Configuration Acuator ###
# Exponer todos los endpoints web (*: health, info, metrics, env, loggers, etc.)
management.endpoints.web.exposure.include=*

# Mostrar siempre los detalles de salud (BD, Eureka, Disco)
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.endpoint.health.diskspace.enabled=true

# Mostrar información del sistema operativo en /actuator/info
management.endpoint.info.os.enabled=true

# Opcional recomendado: Habilitar trazabilidad de peticiones HTTP
management.trace.http.enabled=true
