server:
  port: 8081
#  servlet:
#    context-path: /api/v1

spring:
  application:
    name: msvc-flights
  profiles:
    active: dev

  # Base de Datos y JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  # Configuración de Flyway (Al mismo nivel que jpa)
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    out-of-order: true
    clean-disabled: true
    validate-on-migrate: true

  # Docker Compose
  docker:
    compose:
      enabled: false

  # Spring Cloud & Feign Circuit Breaker
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
    circuitbreaker:
      resilience4j:
        enabled: true

# Configuración de Resilience4j (Nivel raíz)
resilience4j:
  circuitbreaker:
    instances:
      default:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000ms
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true
  timelimiter:
    instances:
      default:
        timeout-duration: 3s

# 🟢 4to Pilar: RETRY (Reintentos automáticos ante parpadeos de red)
  retry:
    instances:
      default:
          max-attempts: 3                  # Intentará máximo 3 veces antes de fallar
          wait-duration: 1000ms             # Espera 1 segundo entre el intento 1 y 2
          enable-exponential-backoff: true  # Multiplica el tiempo de espera (1s -> 2s -> 4s)
          exponential-backoff-multiplier: 2
          retry-exceptions:
              - java.io.IOException           # Reintenta solo ante fallos reales de red/conexión
              - feign.FeignException

# Logging (Nivel raíz)
logging:
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

# Eureka Client (Nivel raíz)
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/